# Generated by Django 3.2.25 on 2024-06-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_item_name', models.CharField(max_length=35, verbose_name='Name')),
                ('product_item_slug', models.SlugField(max_length=35)),
                ('product_item_cost', models.FloatField()),
                ('product_item_description', models.TextField()),
                ('product_item_image', models.ImageField(blank=True, default='shop/images/default.jpg', null=True, upload_to='products/product_item_images/')),
            ],
            options={
                'verbose_name': 'name',
                'verbose_name_plural': 'Names',
                'ordering': ['-pk'],
            },
        ),
    ]
